from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
)
from typing import Literal
from secure_domain.shared.models import ErrorModel


class ErrorMessageModel(BaseModel):
    """
    Represents an error message generated by the agent during execution.
    This message part is used convey information about failures allowing the client or user to
    handle exceptions gracefully.
    """

    model_config = ConfigDict(extra="forbid")

    error: ErrorModel = Field(description="Error returned by the agent.")

    type: Literal["error"] = "error"
